### ISSUE TITLE
Use your constants

### ISSUE THREAD

**Issue by AlexKap23** [Sosa09/Slot_Machine#1]
https://github.com/Sosa09/Slot_Machine/blob/79f11c8d9891e43417178aa5bf6f7d9aa325d354/Slot_Machine/Program.cs#L33

Min and max spin values can change. Use your constant so that your code will auto adjust.

**Comment by Sosa09** [comment]
implemented two constants MINIMUM_BET and MAXIMUM__BET and adpater the useroutput
