### ISSUE TITLE
Maybe a switch statement can make this cleaner

### ISSUE THREAD

**Issue by AlexKap23** [Sosa09/Slot_Machine#6]
https://github.com/Sosa09/Slot_Machine/blob/350c0b0223b911445433fe2727e8b4e2cac64d4d/Slot_Machine/UserInterface.cs#L98-L103

You are using if and return statements that make the else if statements kind of redundant. We suggest to try and use a switch statement here to improve the code readability and maintainability.

**Comment by Sosa09** [comment]
I change 2 of if elseif statement the one you mention and have a look at program.cs :)
it makes it more readable
