### ISSUE TITLE
Logic should never invoke UI

### ISSUE THREAD

**Issue by AlexKap23** [Sosa09/Slot_Machine#7]
https://github.com/Sosa09/Slot_Machine/blob/350c0b0223b911445433fe2727e8b4e2cac64d4d/Slot_Machine/Logic.cs#L52

As we have discussed, logical method should never invoke UI. It's kind of okay to do the oposite (so UI invoking logic) but if you can avoid that it's much better. That's why you have your program.cs for.

In this situation, the method is pure logical so it is correct. But the invokation of the UI method is not. So remove that from here and add it to the Program since this logical method returns back winnerAreaCount, so you know  if there's a win or not.

Same thing applies to GetVerticalTotalWinningAreas and GetDiagonalTotalWinningAreas

**Comment by Sosa09** [comment]
...😢 i missed that one ! i have to be more ccarefull in the future

this has been fixed now added to program.cs checking for winningAreaCount and returning the message if winningAreacount greather than 1
